.github/workflows/main.yml

removed pr review from gh actions

---

App.tsx
screens/SignInScreen.tsx
screens/WelcomeScreen.tsx

Change sign in button in sign in page to use our custom component. Change endpoint to correct location. Welcome page font change.
None.

Touchups for the demo

---

navigation/index.tsx
screens/ForgotPasswordScreen.tsx
tsconfig.json

Added a back button to the sign in and sign up screens. It goes back in the navigation stack and is not a simple link back to the welcome page. This could either be a good or a bad thing. 
- [User Authentication](https://github.com/ps-toronto-team-4/.github/issues/5)
None.

P5 hark back button

---

apollo.config.js
components/Queries.graphql
components/generated.ts
navigation/LinkingConfiguration.ts
navigation/index.tsx
package-lock.json
package.json
screens/BudgetScreen.tsx
screens/ExpensesScreen.tsx
screens/ProfileScreen.tsx
screens/ReportsScreen.tsx
screens/ViewExpense.tsx
types.tsx

Created boilerplate for screens and tabs. Expense list created. Warning: passwordHash is hardcoded when fetching expense list.
- [Expenses](https://github.com/ps-toronto-team-4/.github/issues/8)
I love cats.

C8 expenses

---

screens/SignInScreen.tsx

Forgot to push one last change that removes getData function since it is redundant.
- [Sign In Page](https://github.com/ps-toronto-team-4/.github/issues/7)

getData removed

---

package-lock.json
package.json

FIXed package version conflict. Won't crash on android.

---

constants/Colors.ts
hooks/useColorScheme.ts

Disabled dark theme. One line change.
No review needed.

Disabled dark theme.

---

screens/ExpensesScreen.tsx
screens/SignInScreen.tsx

List fixes and added highlighting
CURRENTLY LIMITING DISPLAY TO 20

list fixes

---

hooks/useAuth.tsx
navigation/index.tsx
screens/CategoryScreens/CreateCategoryScreen.tsx

Fixed requests sent with useQuery. Adjusted header style. Refactor code to slim down on the state variable bloat.
- [Create Category](https://github.com/ps-toronto-team-4/.github/issues/10)
None

P10 Resolve query issues + other improvements

---

components/AddButton.tsx
components/DropdownRow.tsx
components/ExpenseEditForm.tsx
hooks/useAuthRedirect.tsx
screens/ExpensesScreen.tsx
screens/SignInScreen.tsx
screens/SignUpScreen/SignUpScreen.tsx
screens/UpdateExpenseScreen.tsx
screens/WelcomeScreen.tsx

Fixed add expense button not working. Fixed bugs on add/update expense screen. Clicking out of fields now blurs/closes them. Also, if you are already logged in and enter an auth screen (like the welcome screen, sign in/sign up screens), you will be redirected to the root screen.
- [Adding/Updating Expense bugs](https://github.com/ps-toronto-team-4/.github/issues/34)
None

Many bugfixes

---

.github/workflows/ghpages.yml

add deployment workflow

---

components/Button.tsx
components/ExpenseDisplay.tsx
components/Queries.graphql
components/generated.ts
hooks/useAuth.tsx
navigation/index.tsx
screens/ExpenseDetailsScreen.tsx
screens/ExpensesScreen.tsx

Prettify expenses list screen and redo most of the code. Remove the swipeable code. Use FlatList instead of scroll view for optimal rendering. Made a few other optimizations. Implemented infinite scroll. Make a component for the ExpenseDisplay.
- [Expenses]https://github.com/ps-toronto-team-4/.github/issues/8)
None.

Hark prettify expenses

---

components/GraphDisplays/byCategory.tsx
screens/ReportsScreen.tsx
yarn-error.log

Merged C35 into P35 Hotfix and now PR
- [Spending by Category Chart](https://github.com/ps-toronto-team-4/.github/issues/44)

P35 hotfix reports

---

components/profile/SettingsBar.tsx
components/profile/UserDetail.tsx
navigation/LinkingConfiguration.ts
navigation/index.tsx
screens/ProfileScreen.tsx
screens/SettingsScreen.tsx
types.tsx

Created profile screen. Renamed it to Settings.
None

Profile hark

---

components/BudgetCategory.tsx
components/PencilButton.tsx
screens/ExpenseDetailsScreen.tsx

Change the three dots to a pencil in budgets.
None

Change the three dots to a pencil in budgets.

---

screens/UserAuthScreens/WelcomeScreen.tsx

Slightly prettier welcome screen.
None

Slightly prettier welcome screen.

---

app.json

Fixed the issue with the permissions JSON I added earlier today

fixed permissions json issue

---

components/graphs/MonthlyExpenses.tsx
components/graphs/MonthlyVsBudgeted.tsx
components/graphs/monthlyVsBudgetedCategory.tsx
screens/ReportScreens/ExpandBarCat.tsx
screens/ReportsScreen.tsx

P35 calvin

---

components/forms/DropdownField.tsx

Hark fixes dropdown

---

components/forms/DropdownField.tsx
components/graphs/ByCategory.tsx
screens/ReportsScreen.tsx

Hark pie improvements

---

components/expenseFilter.tsx
constants/Months.ts
screens/ExpensesScreen.tsx

added filter functionality to the expense list

Hf calvin filter

---

components/budget/TopBar.tsx
components/graphs/ByCategory.tsx
components/graphs/MonthlyVsBudgeted.tsx
components/graphs/monthlyVsBudgetedCategory.tsx
screens/Budget/BudgetScreen.tsx
screens/ReportScreens/ExpandBarCat.tsx
screens/ReportScreens/ExpandBudget.tsx
screens/ReportScreens/ExpandWheel.tsx
screens/ReportsScreen.tsx

Insights now fully functional. 
Reports now fully functional. 
Reports legends are centered.
Pie Chart now shows values.
Month Navigation Bar same as Budget Tab

P39 nasih insights

---

screens/MerchantScreens/CreateMerchantScreen.tsx
screens/ReportScreens/ExpandExpense.tsx
screens/ReportScreens/ExpandWheel.tsx
screens/ReportsScreen.tsx
screens/UserAuthScreens/SignInScreen.tsx

Few bugs within Reports that have been squashed.

ExpandExpenses bugs fixed

---

components/buttons/FilterButton.tsx
components/expenseFilter.tsx
components/filter/ExpenseFilter.tsx
screens/ExpensesScreen.tsx

Slightly better looking filter.

---

screens/CategoryScreens/CategorySettingsScreen.tsx
screens/MerchantScreens/MerchantSettingsScreen.tsx

Change the 'Add Category' and 'Add Merchant' buttons in the category and merchant settings screens from the circular button in the bottom right to a row.
None

Better add buttons for category and merchant

---

components/budget/BudgetCategory.tsx
components/budget/ChartDisplay.tsx

Hf hark rename budgets

---

screens/UserAuthScreens/SignInScreen.tsx
screens/UserAuthScreens/SignUpScreen.tsx

Fix race condition. Now only navigate to root once passwordHash is set in local storage.
None

Fix login/signup redirect bug.

---

screens/HomeScreen.tsx

Now the average monthly spendings for this year only considers expenses for current year.
None

Now the average monthly spendings for this year only considers expenses for current year.

---

components/graphs/ByCategory.tsx

No longer show 'Uncategorized' in pie dropdown if there is no uncategorized expenses.
None

Hotfix insights pie graph

---

screens/UserAuthScreens/SignInScreen.tsx

Fixed login issue. For real this time.
